/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ZME8RO19aQ8
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/


import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { SelectValue, SelectTrigger, SelectContent, Select, SelectItem } from "@/components/ui/select"
import { Button } from "@/components/ui/button"
import { ContextMenuTrigger, ContextMenuItem, ContextMenuContent, ContextMenu } from "@/components/ui/context-menu"

export default function reg() {
  return (
    <div className="bg-white dark:bg-gray-950 py-12 sm:py-16 lg:py-20">
      <div className="mx-auto max-w-4xl space-y-12 px-4 sm:px-6 md:px-8 lg:px-10">
        <div className="space-y-6 text-center">
          <h1 className="text-4xl font-bold tracking-tight sm:text-5xl">Registration</h1>
          <p className="text-lg text-gray-500 dark:text-gray-400">Fill out the form to create your account.</p>
        </div>
        <form className="space-y-8">
          <div className="grid grid-cols-1 gap-8 sm:grid-cols-3">
            <div className="space-y-6">
              <Label className="text-sm font-medium" htmlFor="surname">
                Surname
              </Label>
              <Input
                className="rounded-lg border border-gray-200 bg-white px-4 py-3 text-sm shadow-sm transition-colors focus:border-gray-900 focus:outline-none focus:ring-1 focus:ring-gray-900 dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 dark:focus:border-gray-50 dark:focus:ring-gray-50"
                id="surname"
                placeholder="Enter your surname"
                required
              />
            </div>
            <div className="space-y-6">
              <Label className="text-sm font-medium" htmlFor="name">
                Name
              </Label>
              <Input
                className="rounded-lg border border-gray-200 bg-white px-4 py-3 text-sm shadow-sm transition-colors focus:border-gray-900 focus:outline-none focus:ring-1 focus:ring-gray-900 dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 dark:focus:border-gray-50 dark:focus:ring-gray-50"
                id="name"
                placeholder="Enter your name"
                required
              />
            </div>
            <div className="space-y-6">
              <Label className="text-sm font-medium" htmlFor="middle-name">
                Middle Name
              </Label>
              <Input
                className="rounded-lg border border-gray-200 bg-white px-4 py-3 text-sm shadow-sm transition-colors focus:border-gray-900 focus:outline-none focus:ring-1 focus:ring-gray-900 dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 dark:focus:border-gray-50 dark:focus:ring-gray-50"
                id="middle-name"
                placeholder="Enter your middle name"
              />
            </div>
          </div>
          <div className="grid grid-cols-1 gap-8 sm:grid-cols-2">
            <div className="space-y-6">
              <Label className="text-sm font-medium" htmlFor="birthday">
                Birthday
              </Label>
              <div className="grid grid-cols-3 gap-4">
                <Select>
                  <SelectTrigger
                    className="rounded-lg border border-gray-200 bg-white px-4 py-3 text-sm shadow-sm transition-colors focus:border-gray-900 focus:outline-none focus:ring-1 focus:ring-gray-900 dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 dark:focus:border-gray-50 dark:focus:ring-gray-50"
                    id="birthday-day"
                  >
                    <SelectValue placeholder="Day" />
                  </SelectTrigger>
                  <SelectContent />
                </Select>
                <Select>
                  <SelectTrigger
                    className="rounded-lg border border-gray-200 bg-white px-4 py-3 text-sm shadow-sm transition-colors focus:border-gray-900 focus:outline-none focus:ring-1 focus:ring-gray-900 dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 dark:focus:border-gray-50 dark:focus:ring-gray-50"
                    id="birthday-month"
                  >
                    <SelectValue placeholder="Month" />
                  </SelectTrigger>
                  <SelectContent />
                </Select>
                <Select>
                  <SelectTrigger
                    className="rounded-lg border border-gray-200 bg-white px-4 py-3 text-sm shadow-sm transition-colors focus:border-gray-900 focus:outline-none focus:ring-1 focus:ring-gray-900 dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 dark:focus:border-gray-50 dark:focus:ring-gray-50"
                    id="birthday-year"
                  >
                    <SelectValue placeholder="Year" />
                  </SelectTrigger>
                  <SelectContent />
                </Select>
              </div>
            </div>
            <div className="space-y-6">
              <Label className="text-sm font-medium" htmlFor="gender">
                Gender
              </Label>
              <div className="flex items-center gap-6">
                <Select
                  className="rounded-lg border border-gray-200 bg-white px-4 py-3 text-sm shadow-sm transition-colors focus:border-gray-900 focus:outline-none focus:ring-1 focus:ring-gray-900 dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 dark:focus:border-gray-50 dark:focus:ring-gray-50"
                  id="gender"
                  required
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select gender" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="male">Male</SelectItem>
                    <SelectItem value="female">Female</SelectItem>
                    <SelectItem value="other">Other</SelectItem>
                  </SelectContent>
                </Select>
                <Select className="rounded-lg border border-gray-200 bg-white px-4 py-3 text-sm shadow-sm transition-colors focus:border-gray-900 focus:outline-none focus:ring-1 focus:ring-gray-900 dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 dark:focus:border-gray-50 dark:focus:ring-gray-50">
                  <SelectTrigger>
                    <SelectValue placeholder="Select status" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="single">Single</SelectItem>
                    <SelectItem value="married">Married</SelectItem>
                    <SelectItem value="divorced">Divorced</SelectItem>
                    <SelectItem value="widowed">Widowed</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
          </div>
          <div className="space-y-6">
            <Label className="text-sm font-medium" htmlFor="address-street">
              Address
            </Label>
            <div className="grid grid-cols-1 gap-8 sm:grid-cols-2">
              <Select className="rounded-lg border border-gray-200 bg-white px-4 py-3 text-sm shadow-sm transition-colors focus:border-gray-900 focus:outline-none focus:ring-1 focus:ring-gray-900 dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 dark:focus:border-gray-50 dark:focus:ring-gray-50">
                <SelectTrigger id="address-street">
                  <SelectValue placeholder="Street" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="street1">Street 1</SelectItem>
                  <SelectItem value="street2">Street 2</SelectItem>
                  <SelectItem value="street3">Street 3</SelectItem>
                </SelectContent>
              </Select>
              <Input
                className="rounded-lg border border-gray-200 bg-white px-4 py-3 text-sm shadow-sm transition-colors focus:border-gray-900 focus:outline-none focus:ring-1 focus:ring-gray-900 dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 dark:focus:border-gray-50 dark:focus:ring-gray-50"
                id="address-house"
                placeholder="House Number"
              />
            </div>
          </div>
          <div className="grid grid-cols-1 gap-8 sm:grid-cols-2">
            <div className="space-y-6">
              <Label className="text-sm font-medium" htmlFor="email">
                Email
              </Label>
              <Input
                className="rounded-lg border border-gray-200 bg-white px-4 py-3 text-sm shadow-sm transition-colors focus:border-gray-900 focus:outline-none focus:ring-1 focus:ring-gray-900 dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 dark:focus:border-gray-50 dark:focus:ring-gray-50"
                id="email"
                placeholder="Enter your email"
                required
                type="email"
              />
            </div>
            <div className="space-y-6">
              <Label className="text-sm font-medium" htmlFor="phone">
                Phone
              </Label>
              <Input
                className="rounded-lg border border-gray-200 bg-white px-4 py-3 text-sm shadow-sm transition-colors focus:border-gray-900 focus:outline-none focus:ring-1 focus:ring-gray-900 dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 dark:focus:border-gray-50 dark:focus:ring-gray-50"
                id="phone"
                placeholder="Enter your phone number"
                required
                type="tel"
              />
            </div>
          </div>
          <div className="grid grid-cols-1 gap-8 sm:grid-cols-4">
            <div className="space-y-6">
              <Label className="text-sm font-medium" htmlFor="occupation">
                Occupation
              </Label>
              <Select
                className="rounded-lg border border-gray-200 bg-white px-4 py-3 text-sm shadow-sm transition-colors focus:border-gray-900 focus:outline-none focus:ring-1 focus:ring-gray-900 dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 dark:focus:border-gray-50 dark:focus:ring-gray-50"
                id="occupation"
                required
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select occupation" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="student">Student</SelectItem>
                  <SelectItem value="employee">Employee</SelectItem>
                  <SelectItem value="self-employed">Self-Employed</SelectItem>
                  <SelectItem value="retired">Retired</SelectItem>
                  <SelectItem value="unemployed">Unemployed</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-6">
              <Label className="text-sm font-medium" htmlFor="nationality">
                Nationality
              </Label>
              <Select
                className="rounded-lg border border-gray-200 bg-white px-4 py-3 text-sm shadow-sm transition-colors focus:border-gray-900 focus:outline-none focus:ring-1 focus:ring-gray-900 dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 dark:focus:border-gray-50 dark:focus:ring-gray-50"
                id="nationality"
                required
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select nationality" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="usa">USA</SelectItem>
                  <SelectItem value="canada">Canada</SelectItem>
                  <SelectItem value="uk">United Kingdom</SelectItem>
                  <SelectItem value="australia">Australia</SelectItem>
                  <SelectItem value="other">Other</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-6">
              <Label className="text-sm font-medium" htmlFor="religion">
                Religion
              </Label>
              <Select
                className="rounded-lg border border-gray-200 bg-white px-4 py-3 text-sm shadow-sm transition-colors focus:border-gray-900 focus:outline-none focus:ring-1 focus:ring-gray-900 dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 dark:focus:border-gray-50 dark:focus:ring-gray-50"
                id="religion"
                required
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select religion" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="christian">Christian</SelectItem>
                  <SelectItem value="muslim">Muslim</SelectItem>
                  <SelectItem value="hindu">Hindu</SelectItem>
                  <SelectItem value="buddhist">Buddhist</SelectItem>
                  <SelectItem value="other">Other</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-6">
              <Label className="text-sm font-medium" htmlFor="benefits">
                Benefits
              </Label>
              <Select
                className="rounded-lg border border-gray-200 bg-white px-4 py-3 text-sm shadow-sm transition-colors focus:border-gray-900 focus:outline-none focus:ring-1 focus:ring-gray-900 dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 dark:focus:border-gray-50 dark:focus:ring-gray-50"
                id="benefits"
                required
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select benefits" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="health">Health Insurance</SelectItem>
                  <SelectItem value="dental">Dental Insurance</SelectItem>
                  <SelectItem value="vision">Vision Insurance</SelectItem>
                  <SelectItem value="retirement">Retirement Plan</SelectItem>
                  <SelectItem value="none">None</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
        <div className="grid grid-cols-1 gap-8 sm:grid-cols-2">
          <div className="flex flex-col items-center gap-6">
            <div className="relative h-24 w-24">
              <img alt="Take a photo" className="h-full w-full rounded-lg object-cover" src="/placeholder.svg" />
              <Button className="absolute top-0 right-0" size="icon" variant="ghost">
                <XIcon className="h-4 w-4" />
              </Button>
            </div>
            <ContextMenu>
              <ContextMenuTrigger className="flex items-center gap-2 rounded-lg bg-gray-100 px-4 py-2 text-gray-900 hover:bg-gray-200 dark:bg-gray-800 dark:text-gray-50 dark:hover:bg-gray-700">
                <UploadIcon className="h-5 w-5" />
                <span className="text-sm font-medium">Take a photo</span>
              </ContextMenuTrigger>
              <ContextMenuContent className="w-52 rounded-lg border border-gray-300 bg-white px-4 py-2 shadow-lg dark:border-gray-700 dark:bg-gray-800">
                <ContextMenuItem className="flex items-center gap-2 rounded-lg px-2 py-1 hover:bg-gray-100 dark:hover:bg-gray-700">
                  <Input className="hidden" id="picture-upload" type="file" />
                  <span className="text-sm">Take a photo</span>
                </ContextMenuItem>
                <ContextMenuItem className="flex items-center gap-2 rounded-lg px-2 py-1 hover:bg-gray-100 dark:hover:bg-gray-700">
                  <span className="text-sm">Take a photo</span>
                </ContextMenuItem>
              </ContextMenuContent>
            </ContextMenu>
          </div>
          <div className="flex flex-col items-center gap-6">
            <div className="relative h-24 w-24">
              <img
                alt="Scan fingerprint"
                className="h-full w-full rounded-lg object-cover"
                src="/placeholder.svg"
              />
              <Button className="absolute top-0 right-0" size="icon" variant="ghost">
                <XIcon className="h-4 w-4" />
              </Button>
            </div>

            <ContextMenu>
              <ContextMenuTrigger className="flex items-center gap-2 rounded-lg bg-gray-100 px-4 py-2 text-gray-900 hover:bg-gray-200 dark:bg-gray-800 dark:text-gray-50 dark:hover:bg-gray-700">
                <FingerprintIcon className="h-5 w-5" />
                <span className="text-sm font-medium">Scan fingerprint</span>
              </ContextMenuTrigger>
              <ContextMenuContent className="w-52 rounded-lg border border-gray-300 bg-white px-4 py-2 shadow-lg dark:border-gray-700 dark:bg-gray-800">
                <ContextMenuItem className="flex items-center gap-2 rounded-lg px-2 py-1 hover:bg-gray-100 dark:hover:bg-gray-700">
                  <Input className="hidden" id="picture-upload" type="file" />
                  <span className="text-sm">Scan fingerprint</span>
                </ContextMenuItem>
                <ContextMenuItem className="flex items-center gap-2 rounded-lg px-2 py-1 hover:bg-gray-100 dark:hover:bg-gray-700">
                  <span className="text-sm">Scan fingerprint</span>
                </ContextMenuItem>
              </ContextMenuContent>
            </ContextMenu>
          </div>
        </div>
        <Button className="w-full" type="submit">
          Register
        </Button>
        </form>
      </div>
    </div>
  )
}

function UploadIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="17 8 12 3 7 8" />
      <line x1="12" x2="12" y1="3" y2="15" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
function FingerprintIcon(props) {
    return (
      <svg
        {...props}
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M12 10a2 2 0 0 0-2 2c0 1.02-.1 2.51-.26 4" />
        <path d="M14 13.12c0 2.38 0 6.38-1 8.88" />
        <path d="M17.29 21.02c.12-.6.43-2.3.5-3.02" />
        <path d="M2 12a10 10 0 0 1 18-6" />
        <path d="M2 16h.01" />
        <path d="M21.8 16c.2-2 .131-5.354 0-6" />
        <path d="M5 19.5C5.5 18 6 15 6 12a6 6 0 0 1 .34-2" />
        <path d="M8.65 22c.21-.66.45-1.32.57-2" />
        <path d="M9 6.8a6 6 0 0 1 9 5.2v2" />
      </svg>
    )
  }